# Generated by Django 5.2.5 on 2025-08-17 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0002_liftattempt_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liftattempt',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, message='Ciężar musi być dodatni.')]),
        ),
        migrations.AddConstraint(
            model_name='liftattempt',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='weight_positive'),
        ),
    ]
