# Generated by Django 4.2.21 on 2025-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SQ', 'Squat'), ('BP', 'Bench press'), ('DL', 'Deadlift')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
