# Generated by Django 5.1.5 on 2025-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lift_type', models.CharField(choices=[('SQ', 'Squat'), ('BP', 'Bench press'), ('DL', 'Deadlift')], max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('video', models.FileField(upload_to='videos/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
